# Generated by Django 2.2.12 on 2023-01-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('assignedTo', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=250)),
            ],
        ),
    ]
