# Generated by Django 4.1.4 on 2023-01-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0008_alter_comment_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
    ]
