# Generated by Django 4.1.4 on 2023-01-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0013_remove_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.TextField(default="Type your name here", max_length=25),
        ),
    ]
