# Generated by Django 4.1.4 on 2023-01-04 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0007_supply_qty"),
        ("main_app", "0014_comment_author"),
    ]

    operations = []
