# Generated by Django 4.1.4 on 2023-01-05 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0016_alter_supply_qty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supply",
            name="qty",
        ),
    ]
